server:
  port: 8084

spring:
  application:
    name: review
  datasource:
    url: jdbc:mysql://localhost:3306/reviewed?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect